### ISSUE TITLE
Crashes at [self removeFromSuperview]

### ISSUE THREAD

**Issue by nanothread59** [vibrazy/letterpressexplosion#13]
This tweak crashes my iOS 8 app (I've merged it with my Swift code) after the CAAnimation finishes and it calls [self removeFromSuperview].
Any idea why this is?

Thanks.

**Comment by TheSafo** [comment]
Having this issue too... Sometimes it works when you remove all subviews from the view that you are exploding but not always.

**Comment by vibrazy** [comment]
What are you trying to explode? I will try and replicate

**Comment by nanothread59** [comment]
Sorry, it was so long ago that I can't quite remember. I suspect, however, that it was either a circular UIView (corner radius half of width) or a UIImageView. Probably the first one though.

**Comment by bcattle** [comment]
This appears to happen if you explode a view that has an additional sublayer attached to the main layer. Breaking on line 220 (the offending line) and calling `[view.layer.sublayers firstObject] removeFromSuperlayer]` fixed this for me.

**Comment by bcattle** [comment]
I get this issue when my view has a single UIImageView inside it.

The problem is the line `[[self.layer sublayers] makeObjectsPerformSelector:@selector(removeFromSuperlayer)];` If your view has subviews this line removes the layers belonging to your view's subviews without actually removing the subviews. 

UIViews must apparently hold weak references to their layers, because the layers are disposed of, then the code crashes later on `removeFromSuperview`, presumably because the subviews are being traversed, and any reference to the subview's now dealloc'd CALayer is a BAD_ACCESS.

I added 

    [[self subviews] makeObjectsPerformSelector:@selector(removeFromSuperview)];

before the 

    [[self.layer sublayers] makeObjectsPerformSelector:@selector(removeFromSuperlayer)]; 

And that resolved this issue for me.

**Comment by vijayvir** [comment]
In my case, I was adding layers in UiButton in draw rect, And remove the all layers at  action Tap , But It gives the error, Beacuse sublayers had UIlabel layer That was also removing, so Solve this issue I added the  names to my layers and It solved My issues as This time I am only deleting that which have name that I had defined.
